# Generated by Django 5.1.3 on 2024-12-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gender_user_language_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('KRW', 'Korean Won'), ('USD', 'US Dollar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('KR', 'Korean'), ('EN', 'English')], max_length=10),
        ),
    ]
