# Generated by Django 5.1.3 on 2024-12-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('year', models.PositiveBigIntegerField()),
                ('area', models.PositiveIntegerField(help_text='m²')),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.FloatField()),
                ('floors', models.PositiveIntegerField()),
                ('parking', models.BooleanField()),
                ('garden', models.BooleanField()),
                ('pool', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='houses/images')),
                ('pets_allowed', models.BooleanField(default=False, verbose_name='Pets allowed?')),
            ],
        ),
    ]
