# Generated by Django 5.1.3 on 2024-12-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_cateogry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='cateogry',
            new_name='category',
        ),
    ]
